name: Release Sims
# Release Sims workflow runs long-lived (multi-seed & large block size) simulations of 500 blocks.
# This workflow only runs on a pull request when the branch contains rc** (rc1/vX.X.x)
# This release workflow *cannot* be skipped with the 'skip-sims' commit message.
on:
  pull_request:
    branches:
      - "rc**"

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/development'"

  install-runsim:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-sims')"
    steps:
      - name: install runsim
        run: |
          export GO111MODULE="on" && go get github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v2.1.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  test-sim-multi-seed-long:
    runs-on: ubuntu-latest
    needs: install-runsim
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test-sim-multi-seed-long
        run: |
          make test-sim-multi-seed-long
